### ISSUE TITLE
Babel Build Error

### ISSUE THREAD

**Issue by senpng** [ProjectSeptemberInc/gl-react-dom#3]
```bash
~/Documents/Git/React/ReactNative/gl-react-dom on  master 🕒  18:33:36
$ babel --source-maps -d lib src
SyntaxError: src/GLCanvas.js: A semicolon is required after a class property (262:3)
  260 |       return fbo;
  261 |     }
> 262 |   }
      |    ^
  263 | 
  264 |   _syncData (data) {
  265 |     // Synchronize the data props that contains every data needed for render
```

**Comment by gre** [comment]
why do you need to execute babel yourself? The library is supposed to be published on NPM without need to use babel.
That said I'll fix this, it's a new breaking change of recent babel version

**Comment by senpng** [comment]
I want to look example. and I need to build bundle.js.

I see that you have solved this problem.

I not understand add the semicolon.

I think the semicolon is not needed in ES6.

**Comment by gre** [comment]
for ref: https://phabricator.babeljs.io/T6873

**Comment by senpng** [comment]
Thinks,I see.
