### ISSUE TITLE
Can not find the file or code of advanced effects examples?

### ISSUE THREAD

**Issue by popozy** [ProjectSeptemberInc/gl-react-dom#7]

**Comment by popozy** [comment]
I'm confused by 404 page when I wanna to see the code of the advanced effects examples, which is react-native version. So.. what's wrong with it?:)

**Comment by gre** [comment]
sorry for the broken links.

it's here https://github.com/ProjectSeptemberInc/gl-react-native/tree/master/example/src/AdvancedEffects

inside the example app https://github.com/ProjectSeptemberInc/gl-react-native/tree/master/example/

if you see other dead link, feel free to provide a PR
